version: '3'

services:

  nginx:
    build: docker/nginx
    ports:
      - 7007:80
    depends_on:
      - web

  web:
    env_file:
      - .env
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - .:/code
    expose:
      - 8000

