# Generated by Django 4.0.5 on 2022-06-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_completed', models.CharField(max_length=256)),
                ('manufacturer', models.CharField(max_length=256)),
                ('physical_class', models.CharField(max_length=256)),
                ('nb_engines', models.CharField(max_length=256)),
                ('aac', models.CharField(max_length=256)),
                ('adg', models.CharField(max_length=256)),
                ('tdg', models.CharField(max_length=256)),
                ('approach_speed', models.CharField(max_length=256)),
                ('wingtip_config', models.CharField(max_length=256)),
                ('wingspan', models.CharField(max_length=256)),
                ('length', models.CharField(max_length=256)),
                ('model', models.CharField(max_length=256)),
                ('tail_height', models.CharField(max_length=256)),
                ('wheel_base', models.CharField(max_length=256)),
                ('cmg', models.CharField(max_length=256)),
                ('mgw', models.CharField(max_length=256)),
                ('mtow', models.CharField(max_length=256)),
                ('max_ramp', models.CharField(max_length=256)),
                ('main_gear_config', models.CharField(max_length=256)),
                ('icao_code', models.CharField(max_length=256)),
                ('wake_category', models.CharField(max_length=256)),
                ('atct_weight_class', models.CharField(max_length=256)),
                ('years_manufactured', models.CharField(max_length=256)),
                ('notes', models.CharField(max_length=256)),
                ('tags', models.CharField(max_length=256)),
            ],
        ),
    ]
